Обновлена версия net до 8
Byndyusoft/Byndyusoft.AspNetCore.Instrumentation.Tracing pull request #11
Opened 2024-02-28 13:29 UTC by jva44ka

2024-02-29 04:40 UTC, Rinatich requested changes, later dismissed

2024-02-29 04:40 UTC, Rinatich commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/Byndyusoft.AspNetCore.Instrumentation.Tracing.csproj
> -		<TargetFrameworks>netstandard2.0;netcoreapp3.1;net6.0</TargetFrameworks>
Почему убрал netcoreapp3.1?

2024-02-29 04:40 UTC, Rinatich commented on tests/Byndyusoft.AspNetCore.Instrumentation.Tracing.Tests.csproj
> -		<TargetFrameworks>netcoreapp3.1;net6.0</TargetFrameworks>
Почему убрал netcoreapp3.1?

2024-12-05 13:54 UTC, NikolayKorsakov commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/Byndyusoft.AspNetCore.Instrumentation.Tracing.csproj
> -		<TargetFrameworks>netstandard2.0;netcoreapp3.1;net6.0</TargetFrameworks>
Больше не поддерживается на osx

2024-12-05 14:31 UTC, litichevskiydv requested changes

2024-12-05 14:31 UTC, litichevskiydv commented on example/Startup.cs
> +                .WithTracing
Исправить форматирование: перенести `(` на строку выше и исправить отступы перед `{`. После этого отформатить файл целиком

2024-12-05 14:31 UTC, litichevskiydv commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/Byndyusoft.AspNetCore.Instrumentation.Tracing.csproj
> +		<PackageReference Include="System.Diagnostics.DiagnosticSource" Version="9.0.0" />
Установить версию `8.0.0`, поскольку переходим на .NET 8

2024-12-05 14:31 UTC, litichevskiydv commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/Byndyusoft.AspNetCore.Instrumentation.Tracing.csproj
> +		<PackageReference Include="System.Text.Json" Version="9.0.0" />
Установить версию `8.0.0`, поскольку переходим на .NET 8

2024-12-05 14:31 UTC, litichevskiydv commented on tests/Byndyusoft.AspNetCore.Instrumentation.Tracing.Tests.csproj
> +		<PackageReference Include="OpenTelemetry" Version="1.10.0" />
Нам точно нужны пакеты `OpenTelemetry` в тестах?

2024-12-05 14:31 UTC, litichevskiydv commented on tests/Byndyusoft.AspNetCore.Instrumentation.Tracing.Tests.csproj
> +		<PackageReference Include="Byndyusoft.MaskedSerialization.Newtonsoft" Version="3.0.0" />
Нам нужен этот пакет в тестах?

2024-12-05 18:54 UTC, litichevskiydv commented on example/Byndyusoft.AspNetCore.Instrumentation.Tracing.Example.csproj
> +		<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.10.0" />
Убрать пакет, он не для прода

2024-12-05 18:55 UTC, litichevskiydv commented on tests/Functional/FunctionalTests.cs
>              });
Перенести `);` на новую строчку и отформатировать

2024-12-05 18:56 UTC, litichevskiydv commented on tests/Functional/FunctionalTests.cs
> +                .WithTracing(tracing =>
Перенести `tracing =>` на новую строчку и отформатировать

2024-12-06 05:47 UTC, NikolayKorsakov commented on tests/Byndyusoft.AspNetCore.Instrumentation.Tracing.Tests.csproj
> -		<TargetFrameworks>netcoreapp3.1;net6.0</TargetFrameworks>
Больше не поддерживается на osx, проверки гит экшенов проваливаются при попытке его скачать

2024-12-06 16:19 UTC, litichevskiydv requested changes

2024-12-06 16:19 UTC, litichevskiydv commented on tests/Functional/FunctionalTests.cs
> +                                options => { options.EnrichWithHttpRequest = (activity, _) => _activity = activity; });
Перенести `);` на следующую строчку и отформатировать

2024-12-06 16:26 UTC, litichevskiydv approved these changes, later dismissed

2024-12-06 16:26 UTC, litichevskiydv commented on example/Startup.cs
> +                                })
Перенести `)` на следующую строку и отформатировать.

2024-12-06 16:26 UTC, litichevskiydv commented on example/Startup.cs
> +                    });
Перенести `);` на следующую строку и отформатировать

2024-12-09 09:45 UTC, litichevskiydv approved these changes

2024-12-09 11:40 UTC, merged