Feature/145 instrumentation
Byndyusoft/Byndyusoft.AspNetCore.Instrumentation.Tracing pull request #13
Opened 2024-05-23 08:28 UTC by Rinatich

Добавил логирование дополнительных данных в трассировку и в логи

2024-05-29 16:30 UTC, litichevskiydv submitted a review, later dismissed

2024-12-12 20:13 UTC, litichevskiydv requested changes

2024-12-12 20:13 UTC, litichevskiydv commented on .github/workflows/pushOrPullRequest.yml
> +        os: [ubuntu-latest, windows-latest]
Добавь `macos-latest`

2024-12-12 20:13 UTC, litichevskiydv commented on README.md
> +```csharp
Вернуть `shell`, поскольку это консольная команда

2024-12-12 20:13 UTC, litichevskiydv commented on README.md
> +                    options.LogRequestInTrace = false;
Убрать отсутствующие флаги

2024-12-12 20:13 UTC, litichevskiydv commented on example/Byndyusoft.AspNetCore.Instrumentation.Tracing.Example.csproj
> +		<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.10.0" />
Убрать пакет, его не рекомендуют использовать в проде

2024-12-12 20:13 UTC, litichevskiydv commented on example/Byndyusoft.AspNetCore.Instrumentation.Tracing.Example.csproj
>  	<ItemGroup>
Выровнять отступы

2024-12-12 20:13 UTC, litichevskiydv commented on example/Program.cs
>      .GetValue<string>("Jaeger:ServiceName");
Поставить `!` перед `;`

2024-12-12 20:13 UTC, litichevskiydv commented on example/Program.cs
> +        resource => resource.AddService(serviceName!)
Убрать `!`, поставим его выше

2024-12-12 20:13 UTC, litichevskiydv commented on example/Program.cs
> +                .AddConsoleExporter();
Убрать, поскольку этот экспортер не рекомендован к использованию в проде

2024-12-12 20:13 UTC, litichevskiydv commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/AspNetMvcRequestTracingFilter.cs
> +            IOptions<AspNetMvcTracingOptions> options)
Перенести `)` на новую строку и отформатировать

2024-12-12 20:13 UTC, litichevskiydv commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/AspNetMvcRequestTracingFilter.cs
> +            _logger = logger;
Проверить `logger` на `null` при помощи `Guard.NotNull`

2024-12-12 20:13 UTC, litichevskiydv commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/AspNetMvcRequestTracingFilter.cs
>              CancellationToken cancellationToken)
Перенести `)` на следующую строку и отформатировать

2024-12-12 20:13 UTC, litichevskiydv commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/AspNetMvcRequestTracingFilter.cs
Перенести `)` на следующую строку и отформатировать

2024-12-12 20:13 UTC, litichevskiydv commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/AspNetMvcRequestTracingFilter.cs
> +            CancellationToken cancellationToken)
Перенести `)` на следующую строку и отфорамтировать

2024-12-12 20:13 UTC, litichevskiydv commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/AspNetMvcRequestTracingFilter.cs
> +            public string Body { get; }
Убрать, поскольку мы не знаем что это такое по факту и можем случайно залогировать конфиденциальную информацию. Извлекаем только типизованные данные из параметров, где мы можем управлять сериализациией.

2024-12-12 20:13 UTC, litichevskiydv commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/AspNetMvcRequestTracingFilter.cs
> +                return;
Добавить отступ для отделения досрочного выхода из метода

2024-12-12 20:13 UTC, litichevskiydv commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/AspNetMvcRequestTracingFilter.cs
> +            RequestContextParameter[] requestContextParameters)
Перенести `)` на следующую строку и отформатировать

2024-12-12 20:13 UTC, litichevskiydv commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/AspNetMvcRequestTracingFilter.cs
> +        private static async Task<RequestContext> BuildRequestContext(
Пернести `ActionExecutingContext context)` на предыдущую строку, заголовок достаточно короткий и его нет смысла разбивать на две строчки

2024-12-12 20:13 UTC, litichevskiydv commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/AspNetMvcRequestTracingFilter.cs
> +            var body = "";
Убрать захвать нетипизованного `Body`, это черевато рисками, описал их ниже

2024-12-12 20:13 UTC, litichevskiydv commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/AspNetMvcRequestTracingFilter.cs
> +                body);
Перенести `);` на следующую строку и отформатировать

2024-12-12 20:13 UTC, litichevskiydv commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/AspNetMvcRequestTracingFilter.cs
> +                string body)
Перенести `)` на следующую строку и отформатировать

2024-12-12 20:13 UTC, litichevskiydv commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/AspNetMvcResponseTracingFilter.cs
> +            IOptions<AspNetMvcTracingOptions> options)
Перенести `)` на следующую строку и отформатировать

2024-12-12 20:13 UTC, litichevskiydv commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/AspNetMvcResponseTracingFilter.cs
> +            _logger = logger;
Проверить `logger` на `null` при помощи `Guard.NotNull`

2024-12-12 20:13 UTC, litichevskiydv commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/AspNetMvcResponseTracingFilter.cs
> +        private const string ContentTypeHeader = "http.response.header.content.type";
Заинлайнить константы, поскольку они не переиспользуются и содержимое вполне говорящее

2024-12-12 20:13 UTC, litichevskiydv commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/AspNetMvcResponseTracingFilter.cs
> +        private async Task LogResponseInLogAsync(
Записать параметры в одну строчку, она достаточно короткая и нет смысла разбивать ее на две

2024-12-12 20:13 UTC, litichevskiydv commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/AspNetMvcResponseTracingFilter.cs
> +                body);
Перенести `);` на следующую строку и отформатировать

2024-12-12 20:13 UTC, litichevskiydv commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/AspNetMvcResponseTracingFilter.cs
> +                object? body)
Перенести `)` на следующую строку и отформатировать

2024-12-12 20:13 UTC, litichevskiydv commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/Byndyusoft.AspNetCore.Instrumentation.Tracing.csproj
> +        <PackageReference Include="Byndyusoft.Logging.OpenTelemetry.Abstractions" Version="3.0.1" />
Привести в порядок отступы

2024-12-12 20:13 UTC, litichevskiydv commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/Byndyusoft.AspNetCore.Instrumentation.Tracing.csproj
> +        <PackageReference Include="Byndyusoft.MaskedSerialization.Newtonsoft" Version="3.0.0" />
Убрать пакет, поскольку `NewtonsoftJsonFormatter` был удален

2024-12-12 20:13 UTC, litichevskiydv commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/Serialization/FormatterBase.cs
>              CancellationToken cancellationToken = default)
Перенести `)` и отформатировать

2024-12-12 20:13 UTC, litichevskiydv commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/Serialization/FormatterBase.cs
>              CancellationToken cancellationToken);
Перенести `);`  на следующую строку и отформатировать

2024-12-12 20:13 UTC, litichevskiydv commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/Serialization/IFormatter.cs
>              CancellationToken cancellationToken);
Перенести `);` на следующую строку и отформатировать

2024-12-12 20:13 UTC, litichevskiydv commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/Serialization/Json/SystemTextJsonFormatter.cs
>              CancellationToken cancellationToken)
Перенести `)` на следующую строку и отформатировать

2024-12-12 20:13 UTC, litichevskiydv commented on tests/Functional/Controllers/TestController.cs
> +            return File(Request.Body, "application/octet-stream");
Убрать, поскольку мы не будем логировать нетипизированный `Body` по причинам, описанным выше

2024-12-12 20:13 UTC, litichevskiydv commented on tests/Functional/FunctionalLoggingTests.cs
> +                });
Перенести `);` на следующую строку и отформатировать

2024-12-12 20:13 UTC, litichevskiydv commented on tests/Functional/FunctionalLoggingTests.cs
> +            var reqMessageStr =GetBodyFromLogger(
Не использовать сокращение в имени переменной `reqMessageStr` и добавить пробел после `=`

2024-12-12 20:13 UTC, litichevskiydv commented on tests/Functional/FunctionalLoggingTests.cs
> +                RequestModelName);
Перенести `);` на следующую строку и отформатировать

2024-12-12 20:13 UTC, litichevskiydv commented on tests/Functional/FunctionalLoggingTests.cs
> +            var resMessageStr = GetBodyFromLogger(
Не использовать сокращение в имени переменной `resMessageStr` и добавить пробел после `=`

2024-12-12 20:13 UTC, litichevskiydv commented on tests/Functional/FunctionalLoggingTests.cs
> +                ResponseBodyName);
Перенести `);` на следующую строку и отформатировать

2024-12-12 20:13 UTC, litichevskiydv commented on tests/Functional/FunctionalLoggingTests.cs
> +            var reqMessageStr =GetBodyFromLogger(
Не использовать сокращение в имени переменной `reqMessageStr` и добавить пробел после `=`

2024-12-12 20:13 UTC, litichevskiydv commented on tests/Functional/FunctionalLoggingTests.cs
> +                RequestModelName);
Перенести `);` на следующую строку и отформатировать

2024-12-12 20:13 UTC, litichevskiydv commented on tests/Functional/FunctionalLoggingTests.cs
> +            var resMessageStr = GetBodyFromLogger(
Не использовать сокращение в имени переменной `resMessageStr` и добавить пробел после `=`

2024-12-12 20:13 UTC, litichevskiydv commented on tests/Functional/FunctionalLoggingTests.cs
> +                ResponseBodyName);
Перенести `);` на следующую строку ии отформатировать

2024-12-12 20:13 UTC, litichevskiydv commented on tests/Functional/FunctionalLoggingTests.cs
> +        public async Task Test_DefaultStreamBehaviour_ExpectedRequestAndResponseLogging()
Зафиксировать в тесте, чтомы не записываем нетипизированное `Body` в логи

2024-12-12 20:13 UTC, litichevskiydv commented on tests/Functional/FunctionalTracingTests.cs
> +                });
Перенести `);` и отформатировать

2024-12-12 20:13 UTC, litichevskiydv commented on tests/Functional/FunctionalTracingTests.cs
> +                                    options.EnrichWithHttpRequest +=
Записать в одну строку, поскольку конструкция достаточно короткая

2024-12-12 20:13 UTC, litichevskiydv commented on tests/Functional/FunctionalTracingTests.cs
> +                @event =>
Записать лямбду в одну строку, поскольку она досттаточно короткая

2024-12-12 20:13 UTC, litichevskiydv commented on tests/Functional/MvcTestFixture.cs
> +            services.AddLogging(c =>
Перенести `c =>` на новую строку и отформатировать

2024-12-12 20:13 UTC, litichevskiydv commented on tests/Functional/MvcTestFixture.cs
> +            });
Перенсти `);` на новую строку и отформатировать

2024-12-12 20:13 UTC, litichevskiydv commented on tests/Utility/TestLogger.cs
> +public class TestLogger(string name) : ILogger
На сколько оправодано написание своей реализации по сравнению с исполььзование `Mock<ILogger>`?

2024-12-13 12:28 UTC, govorovvs requested changes

2024-12-13 12:28 UTC, govorovvs commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/Serialization/Json/SystemTextJsonFormatter.cs
> +            _options = new JsonSerializerOptions();
получать опции для Json из DI
https://stackoverflow.com/questions/61287571/how-to-get-current-jsonserializeroptions-in-asp-net-core-3-1

2024-12-13 12:28 UTC, govorovvs commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/AspNetMvcRequestTracingFilter.cs
> +            if (contentLength.HasValue && !parameters.Any(_ => _.Name.Equals("model")))
откуда взялось имя параметра "model"?

2024-12-16 13:24 UTC, NikolayKorsakov commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/AspNetMvcRequestTracingFilter.cs
В Guard.NotNull?

2024-12-16 15:03 UTC, NikolayKorsakov commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/Serialization/Json/SystemTextJsonFormatter.cs
> +            _options = new JsonSerializerOptions();
Вроде как изначально идея была в том, что опции не обязательны, а в примере они в любом случае подменяются?

2024-12-16 15:28 UTC, govorovvs commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/Serialization/Json/SystemTextJsonFormatter.cs
> +            _options = new JsonSerializerOptions();
При конфигурировании MVC приложения можно задать JSON-настройки. Наверное, имеет смысл эти же настройки использовать и в трассах/логах. 
![image](https://github.com/user-attachments/assets/1a79d860-a6bf-49bc-ada5-bae256709104)

2024-12-18 13:42 UTC, NikolayKorsakov commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/Serialization/Json/SystemTextJsonFormatter.cs
> +            _options = new JsonSerializerOptions();
Насколько я понял, оптимальным решением прокидывания общих опций json сериализации было бы вытащить formatter  из опций трейсинга и добавление его отдельно через ди, но это решение глобальное, и, как мне кажется, под него стоит выделить отдельную задачу.

2024-12-18 13:46 UTC, NikolayKorsakov commented on src/Byndyusoft.AspNetCore.Instrumentation.Tracing/AspNetMvcRequestTracingFilter.cs
> +            if (contentLength.HasValue && !parameters.Any(_ => _.Name.Equals("model")))
А нет его больше, но, как я понял изначально он брался из стандартных параметров запроса в зависимости от типа содержимого: там мог быть файл, могла быть модель, а если там был стрим, то вроде как в параметрах по этому поводу ничего не лежало.

2024-12-18 14:00 UTC, govorovvs approved these changes

2024-12-18 15:08 UTC, litichevskiydv approved these changes

2024-12-19 08:07 UTC, merged